In [1]:
import numpy as np
x= np.arange(6).reshape(3, 2)
print("Original array elements:")
print(x)
print("Array to list:")
print(x.tolist())


Original array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


In [2]:
import numpy as np
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print("\original array1:")
print(x)
print("\original array2:")
print(y)
print("covariance matrix ",np.cov(x, y))

\original array1:
[0 1 2]
\original array2:
[2 1 0]
covariance matrix  [[ 1. -1.]
 [-1.  1.]]


In [4]:
import math

nbs = input("input ")
nbs = nbs.split(',')

result_list = []
for a in nbs:
    b = round(math.sqrt(2 * 50 * int(a) / 30))
    result_list.append(b)

print(result_list)

input  18,22,24


[8, 9, 9]


In [5]:
import math

nbs = input("input ")
nbs = nbs.split(',')

result_list = []
for a in nbs:
    b = round(math.sqrt(2 * 50 * int(a) / 30))
    result_list.append(b)

print(result_list)

input  100,150,180


[18, 22, 24]


In [7]:
def remove_char(str, n):
      p1 = str[:n] 
      p2 = str[n+1:]
      return p1 + p2
print(remove_char('kitten', 1))
print(remove_char('kitten', 0))
print(remove_char('kitten', 4))

ktten
itten
kittn


In [8]:
def factorial(n):
    if n == 0:
        return 1
    else:
        return (n * factorial(n-1))
n=int(input("Input : "))
print(factorial(n))



Input :  8


40320
